spring:
  jpa:
    hibernate:
      ddl-auto: update
      format_sql : true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://springboot-database.cazcki8l5r3x.ap-northeast-2.rds.amazonaws.com:3306/bigtyno
    username: admin
    password: adminadmin
